///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ran_jenkins1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ran_jenkins1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("85298d90-cc7e-4533-88bc-6f866db0f0b1")]
    public partial class Ran_jenkins1Repository : RepoGenBaseFolder
    {
        static Ran_jenkins1Repository instance = new Ran_jenkins1Repository();
        Ran_jenkins1RepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the Ran_jenkins1Repository element repository.
        /// </summary>
        [RepositoryFolder("85298d90-cc7e-4533-88bc-6f866db0f0b1")]
        public static Ran_jenkins1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ran_jenkins1Repository() 
            : base("Ran_jenkins1Repository", "/", null, 0, false, "85298d90-cc7e-4533-88bc-6f866db0f0b1", ".\\RepositoryImages\\Ran_jenkins1Repository85298d90.rximgres")
        {
            _rxmainframe = new Ran_jenkins1RepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85298d90-cc7e-4533-88bc-6f866db0f0b1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("712a03ef-61e6-4f8f-b42c-19bf03a273dc")]
        public virtual Ran_jenkins1RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Ran_jenkins1RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("712a03ef-61e6-4f8f-b42c-19bf03a273dc")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@automationid='RxMainFrame']", parentFolder, 30000, null, true, "712a03ef-61e6-4f8f-b42c-19bf03a273dc", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@automationid='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", ".//text[@accessiblename='Enter your name']", 30000, null, "ff076da4-12da-4d5f-82c4-7d28101b5db1");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", "?/?/button[@accessiblename='Close']", 30000, null, "258c6930-9ea5-414d-a369-17cb41d5b72b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("712a03ef-61e6-4f8f-b42c-19bf03a273dc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("712a03ef-61e6-4f8f-b42c-19bf03a273dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("ff076da4-12da-4d5f-82c4-7d28101b5db1")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("ff076da4-12da-4d5f-82c4-7d28101b5db1")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("258c6930-9ea5-414d-a369-17cb41d5b72b")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("258c6930-9ea5-414d-a369-17cb41d5b72b")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
